// Compares generation strategies on FIXED trained checkpoints:
//
//   greedy      naive baseline: full re-encode + decode per byte
//   selfspec    BLT-S (Fast-BLT section 5.1), k in {4, 8, 16}
//   blockdiff   BLT-D raw drafting (Algorithm 1, do_verify=false)
//   blockdv     BLT-DV (draft + Algorithm 2 verification)
//
// Metrics per config, aggregated over held-out prompts:
//   dec_nfe_per_byte   decoder forward passes / generated byte
//   enc_nfe_per_byte   encoder+global passes / generated byte
//   acceptance         drafted bytes accepted by verification (drafting methods)
//   agreement          fraction of generated positions equal to the SAME
//                      model's greedy output (quality proxy; DV must be 1.0)
//   latency            wall-clock seconds per prompt (bench_stats)
//
// Results append to bench/results.jsonl under experiment group "6_infer" so
// tools/bench_report.py and tools/bench_plots.py can render them.
//
// Build + run:  make bench-infer

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "harness.h"

#include "blt/core/allocator.h"
#include "blt/core/backend.h"
#include "blt/models/model.h"
#include "blt/models/checkpoint.h"
#include "blt/models/entropy_lm.h"
#include "blt/models/patcher.h"
#include "blt/infer/block_generation.h"
#include "blt/infer/self_speculation.h"
#include "generate_greedy.h"

typedef struct {
    const char* ckpt_plain;
    const char* ckpt_bltd;
    const char* heldout_path;
    const char* results_path;
    size_t num_prompts;
    size_t prompt_len;
    size_t new_bytes;
    size_t offset_stride;
    const char* entropy_lm; // optional trained entropy-LM weights
    int fixed_patches;      // 1 = fixed-stride-4 segmentation everywhere
                            // (matches how the checkpoints were trained)
} bench_args;

static const bench_args DEFAULTS = {
    .ckpt_plain = "runs/plain_40k.fblt",
    .ckpt_bltd = "runs/bltd_l03_40k.fblt",
    .heldout_path = "data/heldout.bin",
    .results_path = "bench/results.jsonl",
    .num_prompts = 8,
    .prompt_len = 64,
    .new_bytes = 64,
    .offset_stride = 100000,
    .entropy_lm = NULL,
    .fixed_patches = 0,
};

//----------------------------------------------------------------------
// Shared setup
//----------------------------------------------------------------------

static void build_model_config(blt_model_config* cfg, size_t E, size_t HID,
                               size_t L, size_t MS) {
    memset(cfg, 0, sizeof(*cfg));
    cfg->encoder_config.embed_dim = E; cfg->encoder_config.patch_dim = 0;
    cfg->encoder_config.num_layers = L; cfg->encoder_config.hidden_dim = HID;
    cfg->encoder_config.num_heads = 4; cfg->encoder_config.cross_attn_heads = 4;
    cfg->encoder_config.local_window = 0; cfg->encoder_config.cross_attn_all_layers = true;
    cfg->encoder_config.pool_type = BLT_POOL_MEAN;
    cfg->encoder_config.rope_theta = 500000.0f;
    cfg->encoder_config.max_seq_len = MS;
    cfg->encoder_config.ngram_config.ngram_sizes[0] = 3;
    cfg->encoder_config.ngram_config.ngram_sizes[1] = 4;
    cfg->encoder_config.ngram_config.num_ngram_sizes = 2;
    cfg->encoder_config.ngram_config.per_ngram_vocab = 50;
    cfg->encoder_config.ngram_config.hash_prime = 1000000007ULL;
    cfg->encoder_config.ngram_config.normalize = true;
    cfg->encoder_config.ngram_config.embed_dim = E;
    cfg->global_config.embed_dim = E; cfg->global_config.num_layers = L;
    cfg->global_config.hidden_dim = HID; cfg->global_config.num_heads = 4;
    cfg->global_config.rope_theta = 500000.0f; cfg->global_config.max_seq_len = MS;
    cfg->decoder_config.embed_dim = E; cfg->decoder_config.patch_dim = 0;
    cfg->decoder_config.num_layers = L; cfg->decoder_config.hidden_dim = HID;
    cfg->decoder_config.num_heads = 4; cfg->decoder_config.cross_attn_heads = 4;
    cfg->decoder_config.local_window = 0; cfg->decoder_config.cross_attn_all_layers = true;
    cfg->decoder_config.rope_theta = 500000.0f; cfg->decoder_config.max_seq_len = MS;
    cfg->decoder_config.vocab_size = 256;
}

static void fill_small_uniform(blt_tensor* t, float scale) {
    float* data = (float*)t->data;
    for (size_t i = 0; i < t->numel; i++) {
        float r = ((float)rand() / (float)RAND_MAX) * 2.0f - 1.0f;
        data[i] = r * scale;
    }
}

static blt_entropy_lm* make_entropy_lm(blt_arena* arena, size_t MS,
                                       const char* load_path) {
    blt_entropy_lm_config ecfg;
    memset(&ecfg, 0, sizeof(ecfg));
    ecfg.embed_dim = 32; ecfg.num_layers = 1; ecfg.num_heads = 2;
    ecfg.hidden_dim = 64; ecfg.max_seq_len = MS; ecfg.rope_theta = 10000.0f;
    blt_entropy_lm* lm = blt_entropy_lm_create(arena, &ecfg);
    srand(11);
    fill_small_uniform(&lm->embedding_weight, 0.1f);
    for (size_t i = 0; i < lm->stack.num_layers; i++) {
        blt_transformer_layer_storage* l = &lm->stack.layer_storage[i];
        fill_small_uniform(&l->attn_qkv_w, 0.1f);
        fill_small_uniform(&l->attn_proj_w, 0.1f);
        fill_small_uniform(&l->ffn_up_w, 0.1f);
        fill_small_uniform(&l->ffn_gate_w, 0.1f);
        fill_small_uniform(&l->ffn_down_w, 0.1f);
    }
    fill_small_uniform(&lm->lm_head_weight, 0.1f);
    if (load_path) {
        blt_entropy_lm_load(lm, load_path);
        printf("[INFER-BENCH] entropy LM loaded from %s\n", load_path);
    }
    return lm;
}

static void make_patcher_cfg(blt_patcher_config* pcfg, int fixed) {
    memset(pcfg, 0, sizeof(*pcfg));
    if (fixed) {
        // Disables entropy boundaries: every patch is exactly 4 bytes --
        // the segmentation the checkpoints were trained with.
        pcfg->threshold_global = 1e9f;
        pcfg->threshold_monotonic = 1e9f;
        pcfg->max_patch_length = 4;
    } else {
        pcfg->threshold_global = 2.5f;
        pcfg->threshold_monotonic = 1.0f;
        pcfg->max_patch_length = 16;
    }
    pcfg->rule = BLT_PATCH_RULE_GLOBAL;
    pcfg->reset_on_newline = false;
}

//----------------------------------------------------------------------
// One measurement cell
//----------------------------------------------------------------------

typedef enum {
    M_GREEDY = 0,
    M_SELFSPEC,
    M_BLOCKDIFF,
    M_BLOCKDV,
} method_id;

typedef struct {
    method_id method;
    const char* method_name;
    size_t k_or_B;          // selfspec window or diffusion block size
    float threshold;        // alpha (conf) or gamma (EB)
    int use_eb;             // 1 = EB strategy for diffusion methods
} method_cfg;

typedef struct {
    double dec_per_byte;
    double enc_per_byte;
    double acceptance;      // [0,1]; NaN when nothing drafted
    double agreement;       // fraction of new bytes equal to greedy ref
    double total_drafted;
    double total_accepted;
    double dec_total;
    double enc_total;
} agg_metrics;

// Runs one method over all prompts; fills per-prompt latency samples and
// aggregate counters. Greedy reference for `model` is computed once.
static void run_method(const method_cfg* mc, const blt_model* model,
                       const blt_entropy_lm* lm, const blt_patcher_config* pcfg,
                       uint8_t* const* prompts, uint8_t** refs,
                       uint8_t** scratch_out,
                       const bench_args* a, blt_arena* scratch,
                       double* lat_samples, agg_metrics* agg) {
    memset(agg, 0, sizeof(*agg));

    blt_self_spec_config sc;
    memset(&sc, 0, sizeof(sc));
    sc.window_k = mc->k_or_B;
    sc.d0_mode = BLT_D0_LEARNED;

    blt_block_gen_config gc;
    memset(&gc, 0, sizeof(gc));
    gc.block_size = mc->k_or_B;
    gc.d0_mode = BLT_D0_LEARNED;
    gc.opts.strategy = mc->use_eb ? BLT_UNMASK_EB : BLT_UNMASK_CONFIDENCE;
    gc.opts.threshold = mc->threshold;

    size_t agree_count = 0;
    size_t compare_count = 0;

    for (size_t p = 0; p < a->num_prompts; p++) {
        blt_arena_reset(scratch);

        blt_infer_stats st;
        memset(&st, 0, sizeof(st));
        uint8_t* out = scratch_out[p];

        bench_timer_start();
        switch (mc->method) {
            case M_GREEDY: {
                // Naive baseline counts: one full pipeline pass per byte.
                blt_generate_greedy(model, lm, pcfg, prompts[p], a->prompt_len,
                                    a->new_bytes, out, scratch);
                st.nfe_encoder_global = a->new_bytes;
                st.nfe_decoder = a->new_bytes;
                break;
            }
            case M_SELFSPEC:
                blt_generate_greedy_selfspec(model, lm, pcfg, prompts[p],
                                             a->prompt_len, a->new_bytes, out,
                                             &sc, &st, scratch);
                break;
            case M_BLOCKDIFF:
                blt_generate_greedy_blockdiff(model, lm, pcfg, prompts[p],
                                              a->prompt_len, a->new_bytes, out,
                                              &gc, &st, scratch);
                break;
            case M_BLOCKDV:
                blt_generate_greedy_blockdiff_verify(model, lm, pcfg, prompts[p],
                                                     a->prompt_len, a->new_bytes,
                                                     out, &gc, &st, scratch);
                // DV == greedy holds EXACTLY only when commit points land
                // on patch boundaries (degenerate patchers, controlled
                // unit tests). Real entropy patchers let the final prefix
                // patch absorb draft bytes and greedy itself re-segments
                // per commit, so bench-level equality is approximate; gate
                // on a high-agreement threshold instead of exactness.
                {
                    size_t match = 0;
                    for (size_t j = 0; j < a->new_bytes; j++) {
                        match += (out[a->prompt_len + j] ==
                                  refs[p][a->prompt_len + j]);
                    }
                    if (match < a->new_bytes &&
                        (double)match / (double)a->new_bytes < 0.90) {
                        BLT_FATAL("infer_bench: DV agreement %.2f on prompt "
                                  "%zu (method %s) below 0.90",
                                  (double)match / (double)a->new_bytes,
                                  p, mc->method_name);
                    }
                }
                break;
        }
        lat_samples[p] = bench_timer_stop_sec();

        agg->dec_total += (double)st.nfe_decoder;
        agg->enc_total += (double)st.nfe_encoder_global;
        agg->total_drafted += (double)st.bytes_drafted;
        agg->total_accepted += (double)st.bytes_accepted;

        for (size_t j = 0; j < a->new_bytes; j++) {
            compare_count++;
            if (out[a->prompt_len + j] == refs[p][a->prompt_len + j]) {
                agree_count++;
            }
        }
    }

    const double total_bytes = (double)(a->num_prompts * a->new_bytes);
    agg->dec_per_byte = agg->dec_total / total_bytes;
    agg->enc_per_byte = agg->enc_total / total_bytes;
    agg->acceptance = agg->total_drafted > 0.0
        ? agg->total_accepted / agg->total_drafted : 0.0 / 0.0;
    agg->agreement = (double)agree_count / (double)compare_count;
}

static void write_result(const char* model_tag, const method_cfg* mc,
                         const bench_args* a, const double* lat_samples,
                         const agg_metrics* agg, const char* results_path) {
    bench_result r;
    char tag[BENCH_TAG_LEN];
    snprintf(tag, sizeof(tag), "%s_%s", model_tag, mc->method_name);
    if (mc->method == M_SELFSPEC) {
        char k[16];
        snprintf(k, sizeof(k), "_k%zu", mc->k_or_B);
        strncat(tag, k, sizeof(tag) - strlen(tag) - 1);
    } else if (mc->method == M_BLOCKDIFF || mc->method == M_BLOCKDV) {
        char k[32];
        snprintf(k, sizeof(k), "_B%zu_%s%.2f", mc->k_or_B,
                 mc->use_eb ? "g" : "a", (double)mc->threshold);
        strncat(tag, k, sizeof(tag) - strlen(tag) - 1);
    }

    if (a->fixed_patches) {
        strncat(tag, "_fixp", sizeof(tag) - strlen(tag) - 1);
    }
    bench_result_init(&r, "gen_methods", tag, "6_infer");

    // Latency stats across prompts.
    double* copy = malloc(a->num_prompts * sizeof(double));
    memcpy(copy, lat_samples, a->num_prompts * sizeof(double));
    // bench_stats_compute sorts in place? It takes samples read-only per
    // header contract; pass a copy to be safe.
    bench_stats_compute(&r.latency, copy, a->num_prompts);
    free(copy);

    bench_result_add_metric(&r, "dec_nfe_per_byte", agg->dec_per_byte);
    bench_result_add_metric(&r, "enc_nfe_per_byte", agg->enc_per_byte);
    bench_result_add_metric(&r, "acceptance",
                            agg->total_drafted > 0 ? agg->acceptance : -1.0);
    bench_result_add_metric(&r, "agreement", agg->agreement);
    bench_result_add_metric(&r, "bytes_generated",
                            (double)(a->num_prompts * a->new_bytes));
    bench_result_add_metric(&r, "dec_total", agg->dec_total);
    bench_result_add_metric(&r, "enc_total", agg->enc_total);

    if (bench_write_json(results_path, &r) != 0) {
        BLT_FATAL("infer_bench: cannot write %s", results_path);
    }
}

int main(int argc, char** argv) {
    bench_args a = DEFAULTS;
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--plain") && i + 1 < argc) a.ckpt_plain = argv[++i];
        else if (!strcmp(argv[i], "--bltd") && i + 1 < argc) a.ckpt_bltd = argv[++i];
        else if (!strcmp(argv[i], "--heldout") && i + 1 < argc) a.heldout_path = argv[++i];
        else if (!strcmp(argv[i], "--results") && i + 1 < argc) a.results_path = argv[++i];
        else if (!strcmp(argv[i], "--prompts") && i + 1 < argc)
            a.num_prompts = strtoull(argv[++i], NULL, 10);
        else if (!strcmp(argv[i], "--new-bytes") && i + 1 < argc)
            a.new_bytes = strtoull(argv[++i], NULL, 10);
        else if (!strcmp(argv[i], "--offset-stride") && i + 1 < argc)
            a.offset_stride = strtoull(argv[++i], NULL, 10);
        else if (!strcmp(argv[i], "--fixed-patches"))
            a.fixed_patches = 1;
        else if (!strcmp(argv[i], "--entropy-lm") && i + 1 < argc)
            a.entropy_lm = argv[++i];
    }

    const size_t MS = 512, E = 64, HID = 128, L = 2;

    blt_arena* arena = blt_arena_create(160 * 1024 * 1024, BLT_BACKEND_CPU);
    blt_arena* scratch = blt_arena_create(256 * 1024 * 1024, BLT_BACKEND_CPU);

    blt_model_config cfg;
    build_model_config(&cfg, E, HID, L, MS);

    blt_model* plain = blt_model_create(arena, &cfg);
    blt_model* bltd = blt_model_create(arena, &cfg);
    blt_model_load(plain, a.ckpt_plain);
    blt_model_load(bltd, a.ckpt_bltd);
    printf("[INFER-BENCH] loaded %s + %s\n", a.ckpt_plain, a.ckpt_bltd);

    blt_entropy_lm* lm = make_entropy_lm(arena, MS, a.entropy_lm);
    blt_patcher_config pcfg;
    make_patcher_cfg(&pcfg, a.fixed_patches);
    printf("[INFER-BENCH] patcher: %s\n",
           a.fixed_patches ? "fixed-stride-4" : "entropy (thr 2.5/1.0, max 16)");

    // Held-out prompts at deep offsets.
    FILE* f = fopen(a.heldout_path, "rb");
    if (!f) BLT_FATAL("cannot open %s", a.heldout_path);
    fseek(f, 0, SEEK_END);
    const long esize = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t* heldout = malloc((size_t)esize);
    if (fread(heldout, 1, (size_t)esize, f) != (size_t)esize)
        BLT_FATAL("short read on %s", a.heldout_path);
    fclose(f);

    const size_t need = 2 * a.prompt_len + a.new_bytes;
    uint8_t** prompts = calloc(a.num_prompts, sizeof(uint8_t*));
    uint8_t** refs_p = calloc(a.num_prompts, sizeof(uint8_t*));
    uint8_t** refs_b = calloc(a.num_prompts, sizeof(uint8_t*));
    uint8_t** outs = calloc(a.num_prompts, sizeof(uint8_t*));
    for (size_t p = 0; p < a.num_prompts; p++) {
        const size_t off = 200000 + p * a.offset_stride;
        BLT_REQUIRE(off + need <= (size_t)esize,
                    "heldout too small for prompt offsets");
        prompts[p] = heldout + off;
        refs_p[p] = malloc(a.prompt_len + a.new_bytes);
        refs_b[p] = malloc(a.prompt_len + a.new_bytes);
        outs[p] = malloc(a.prompt_len + a.new_bytes);
    }

    // Greedy references per model.
    for (size_t p = 0; p < a.num_prompts; p++) {
        blt_arena_reset(scratch);
        blt_generate_greedy(plain, lm, &pcfg, prompts[p], a.prompt_len,
                            a.new_bytes, refs_p[p], scratch);
        blt_generate_greedy(bltd, lm, &pcfg, prompts[p], a.prompt_len,
                            a.new_bytes, refs_b[p], scratch);
    }
    printf("[INFER-BENCH] %zu prompts x %zu new bytes ready\n\n",
           a.num_prompts, a.new_bytes);

    static const method_cfg PLAIN_CFGS[] = {
        {M_GREEDY,     "greedy",   0, 0, 0},
        {M_SELFSPEC,   "selfspec", 4, 0, 0},
        {M_SELFSPEC,   "selfspec", 8, 0, 0},
        {M_SELFSPEC,   "selfspec", 16, 0, 0},
    };
    static const method_cfg BLTD_CFGS[] = {
        {M_GREEDY,     "greedy",   0, 0, 0},
        {M_SELFSPEC,   "selfspec", 4, 0, 0},
        {M_SELFSPEC,   "selfspec", 8, 0, 0},
        {M_SELFSPEC,   "selfspec", 16, 0, 0},
        {M_BLOCKDIFF,  "blockdiff", 4, 0.7f, 0},
        {M_BLOCKDIFF,  "blockdiff", 8, 0.7f, 0},
        {M_BLOCKDIFF,  "blockdiff", 16, 0.7f, 0},
        {M_BLOCKDV,    "blockdv",  4, 0.7f, 0},
        {M_BLOCKDV,    "blockdv",  8, 0.7f, 0},
        {M_BLOCKDV,    "blockdv",  16, 0.7f, 0},
        {M_BLOCKDV,    "blockdv_onestep", 8, 0.0f, 0},   // whole block per pass
        {M_BLOCKDV,    "blockdv_eb", 8, 1.0f, 1},
        {M_BLOCKDV,    "blockdv_eb", 8, 2.0f, 1},
        {M_BLOCKDIFF,  "blockdiff_eb", 8, 1.0f, 1},
    };

    double* lat = malloc(a.num_prompts * sizeof(double));
    agg_metrics agg;

    printf("%-28s %10s %10s %10s %10s %12s\n", "tag", "dec/byte",
           "enc/byte", "accept", "agree", "lat_ms_mean");
    printf("%s\n", "--------------------------------------------------------------------------");

    for (size_t i = 0; i < sizeof(PLAIN_CFGS) / sizeof(PLAIN_CFGS[0]); i++) {
        run_method(&PLAIN_CFGS[i], plain, lm, &pcfg,
                   prompts, refs_p, outs, &a, scratch, lat, &agg);
        write_result("plain", &PLAIN_CFGS[i], &a, lat, &agg, a.results_path);
        printf("%-28s %10.3f %10.3f %10.3f %10.3f %12.2f\n", "plain_...",
               agg.dec_per_byte, agg.enc_per_byte,
               agg.total_drafted > 0 ? agg.acceptance : -1.0, agg.agreement,
               1000.0 * lat[0]);
    }
    for (size_t i = 0; i < sizeof(BLTD_CFGS) / sizeof(BLTD_CFGS[0]); i++) {
        run_method(&BLTD_CFGS[i], bltd, lm, &pcfg,
                   prompts, refs_b, outs, &a, scratch, lat, &agg);
        write_result("bltd", &BLTD_CFGS[i], &a, lat, &agg, a.results_path);
        printf("%-28s %10.3f %10.3f %10.3f %10.3f %12.2f\n", "bltd_...",
               agg.dec_per_byte, agg.enc_per_byte,
               agg.total_drafted > 0 ? agg.acceptance : -1.0, agg.agreement,
               1000.0 * lat[0]);
    }

    printf("\n[INFER-BENCH] results appended to %s\n", a.results_path);
    return 0;
}
