// Full-context self-speculation audit: runs one fresh E -> G -> D forward pass
// over an already-generated byte sequence and checks, by greedy argmax, whether
// every committed byte from --prompt-len onward is predicted by that single pass.

#include <float.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "core/allocator.h"
#include "core/backend.h"
#include "core/tensor.h"
#include "models/checkpoint.h"
#include "models/entropy.h"
#include "models/entropy_lm.h"
#include "models/local_decoder.h"
#include "models/model.h"
#include "models/model_builder.h"
#include "models/patcher.h"
#include "ops/softmax.h"

#define AUDIT_MAX_PATCHES 4096

static long fsize(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) return -1;
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fclose(f);
    return sz;
}

// The patcher runs on the host, so device entropy tensors get staged through
// host memory. Returns a malloc'd buffer the caller must free (NULL on CPU).
static const blt_tensor *stage_entropy_host(const blt_tensor *vals, blt_tensor *host_view_out, float **buf_out) {
    if (vals->backend == BLT_BACKEND_CPU) {
        *buf_out = NULL;
        return vals;
    }
    float *buf = (float *)malloc(vals->numel * sizeof(float));
    BLT_REQUIRE(buf != NULL, "stage_entropy_host: allocation failed");
    blt_tensor_download(vals, buf, vals->numel * sizeof(float));
    view_1d(host_view_out, buf, vals->numel, vals->dtype, BLT_BACKEND_CPU);
    *buf_out = buf;
    return host_view_out;
}

// Reproduces compute_entropy_vals from csrc/infer/self_speculation.c: entropy
// LM logits over the bytes, softmax, then per-position entropy (natural log).
static void compute_entropy_vals(blt_arena *arena, const blt_entropy_lm *entropy_model, const uint8_t *bytes,
                                 size_t len, blt_tensor *entropy_vals_out) {
    size_t bytes_shape[1] = {len};
    blt_tensor bytes_in = blt_tensor_create(arena, bytes_shape, 1, BLT_DTYPE_UINT8);
    blt_tensor_upload(&bytes_in, bytes, len);

    size_t logits_shape[2] = {len, 256};
    blt_tensor logits = blt_tensor_create(arena, logits_shape, 2, BLT_DTYPE_FP32);
    size_t scalar_shape[1] = {1};
    blt_tensor discard_loss = blt_tensor_create(arena, scalar_shape, 1, BLT_DTYPE_FP32);

    blt_entropy_lm_forward(entropy_model, &bytes_in, &logits, &discard_loss, arena);

    blt_tensor probs = blt_tensor_create(arena, logits_shape, 2, BLT_DTYPE_FP32);
    blt_softmax(&logits, &probs);

    size_t vals_shape[1] = {len};
    *entropy_vals_out = blt_tensor_create(arena, vals_shape, 1, BLT_DTYPE_FP32);
    blt_entropy_config entropy_cfg = {.vocab_size = 256, .use_log2 = false};
    blt_compute_entropy(&probs, entropy_vals_out, &entropy_cfg);
}

int main(int argc, char **argv) {
    const char *checkpoint = NULL;
    const char *entropy_lm_path = NULL;
    const char *file_path = NULL;
    size_t embed = 0;
    size_t hidden = 0;
    size_t enc_layers = 0;
    size_t glob_layers = 0;
    size_t dec_layers = 0;
    int cross_last = 0;
    long prompt_len = -1;
    long force_l = -1;
    int print_patches = 0;
    int use_cuda = 0;
    double margin_threshold = 0.0;
    uint64_t seed = 11;

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--checkpoint") && i + 1 < argc) checkpoint = argv[++i];
        else if (!strcmp(argv[i], "--entropy-lm") && i + 1 < argc) entropy_lm_path = argv[++i];
        else if (!strcmp(argv[i], "--embed") && i + 1 < argc) embed = (size_t)atol(argv[++i]);
        else if (!strcmp(argv[i], "--hidden") && i + 1 < argc) hidden = (size_t)atol(argv[++i]);
        else if (!strcmp(argv[i], "--enc-layers") && i + 1 < argc) enc_layers = (size_t)atol(argv[++i]);
        else if (!strcmp(argv[i], "--glob-layers") && i + 1 < argc) glob_layers = (size_t)atol(argv[++i]);
        else if (!strcmp(argv[i], "--dec-layers") && i + 1 < argc) dec_layers = (size_t)atol(argv[++i]);
        else if (!strcmp(argv[i], "--cross-attn") && i + 1 < argc) {
            i++;
            if (!strcmp(argv[i], "last")) cross_last = 1;
        } else if (!strcmp(argv[i], "--file") && i + 1 < argc) file_path = argv[++i];
        else if (!strcmp(argv[i], "--prompt-len") && i + 1 < argc) prompt_len = atol(argv[++i]);
        else if (!strcmp(argv[i], "--force-l") && i + 1 < argc) force_l = atol(argv[++i]);
        else if (!strcmp(argv[i], "--backend") && i + 1 < argc) {
            i++;
            if (!strcmp(argv[i], "cuda")) use_cuda = 1;
        } else if (!strcmp(argv[i], "--print-patches")) print_patches = 1;
        else if (!strcmp(argv[i], "--margin-threshold") && i + 1 < argc) margin_threshold = atof(argv[++i]);
        else if (!strcmp(argv[i], "--seed") && i + 1 < argc) seed = (uint64_t)strtoull(argv[++i], NULL, 10);
    }

    if (!checkpoint || !entropy_lm_path || !file_path || prompt_len < 0 || embed == 0 || hidden == 0 ||
        enc_layers == 0 || glob_layers == 0 || dec_layers == 0) {
        fprintf(stderr, "Usage: selfspec_audit --checkpoint FILE --entropy-lm FILE "
                        "--embed N --hidden N --enc-layers N --glob-layers N --dec-layers N "
                        "--file FILE --prompt-len N [--cross-attn all|last] [--force-l N] "
                        "[--backend cpu|cuda] [--print-patches] [--margin-threshold F] [--seed N]\n");
        return 1;
    }
    if (use_cuda) {
        BLT_FATAL("selfspec_audit: --backend cuda is not implemented; use --backend cpu");
    }

    long file_size = fsize(file_path);
    if (file_size <= 0) {
        fprintf(stderr, "Error: cannot read file '%s'\n", file_path);
        return 1;
    }
    const size_t len = (size_t)file_size;
    BLT_REQUIRE(len >= 2, "selfspec_audit: file must hold at least 2 bytes (entropy LM needs seq_len >= 2)");
    BLT_REQUIRE((size_t)prompt_len <= len, "selfspec_audit: --prompt-len (%ld) exceeds file length (%zu)", prompt_len,
                len);
    BLT_REQUIRE(prompt_len >= 1, "selfspec_audit: --prompt-len must be >= 1 (row p-1 predicts byte p)");
    BLT_REQUIRE(force_l >= -1, "selfspec_audit: --force-l must be >= 0");
    if (force_l >= 0) {
        BLT_REQUIRE((size_t)force_l <= len, "selfspec_audit: --force-l (%ld) exceeds file length (%zu)", force_l, len);
    }

    uint8_t *bytes = (uint8_t *)malloc(len);
    BLT_REQUIRE(bytes != NULL, "selfspec_audit: byte buffer allocation failed");
    FILE *f = fopen(file_path, "rb");
    BLT_REQUIRE(f != NULL, "selfspec_audit: cannot open file '%s'", file_path);
    if (fread(bytes, 1, len, f) != len) {
        fclose(f);
        fprintf(stderr, "Error: short read from '%s'\n", file_path);
        free(bytes);
        return 1;
    }
    fclose(f);

    const blt_backend dev = BLT_BACKEND_CPU;
    blt_arena *arena = blt_arena_create(160 * 1024 * 1024, dev);
    blt_arena *scratch = blt_arena_create(256 * 1024 * 1024, dev);

    blt_model_config cfg;
    blt_model_config_defaults(&cfg, embed, hidden, enc_layers, glob_layers, dec_layers, 512, cross_last);
    blt_model *model = blt_model_create(arena, &cfg);
    blt_model_load(model, checkpoint);
    blt_entropy_lm *lm = blt_make_entropy_lm(arena, 512, entropy_lm_path, seed);

    blt_patcher_config pcfg;
    blt_make_patcher_cfg(&pcfg, 0, 2.5f, 1.0f, 16);

    BLT_REQUIRE(len <= cfg.decoder_config.max_seq_len, "selfspec_audit: file length %zu exceeds max_seq_len %zu", len,
                cfg.decoder_config.max_seq_len);

    fprintf(stderr, "[AUDIT] checkpoint: %s\n", checkpoint);
    fprintf(stderr, "[AUDIT] entropy LM: %s (seed=%llu)\n", entropy_lm_path, (unsigned long long)seed);
    fprintf(stderr, "[AUDIT] file: %s (%zu bytes) prompt-len=%ld force-l=%ld\n", file_path, len, prompt_len, force_l);
    fprintf(stderr, "[AUDIT] config: embed=%zu hidden=%zu enc=%zu glob=%zu dec=%zu cross=%s backend=cpu\n", embed,
            hidden, enc_layers, glob_layers, dec_layers, cross_last ? "last" : "all");

    blt_tensor entropy_vals;
    compute_entropy_vals(scratch, lm, bytes, len, &entropy_vals);

    blt_tensor entropy_host_view;
    float *entropy_host_buf = NULL;
    const blt_tensor *entropy_for_patcher = stage_entropy_host(&entropy_vals, &entropy_host_view, &entropy_host_buf);

    blt_patch_info patches[AUDIT_MAX_PATCHES];
    size_t num_patches = blt_segment_patches(entropy_for_patcher, bytes, patches, AUDIT_MAX_PATCHES, &pcfg);
    free(entropy_host_buf);
    entropy_host_buf = NULL;

    if (force_l >= 0) {
        const size_t force_n = (size_t)force_l;
        const size_t before = num_patches;
        size_t splits = 0;
        blt_patch_info forced[AUDIT_MAX_PATCHES];
        size_t n2 = 0;
        for (size_t pi = 0; pi < num_patches && n2 < AUDIT_MAX_PATCHES; pi++) {
            const size_t s = patches[pi].start_idx;
            const size_t e = s + patches[pi].length;
            if (s < force_n && e > force_n) {
                printf("force-l=%ld: split patch start=%zu len=%zu into [%zu,%zu) and [%zu,%zu)\n", force_l, s,
                       patches[pi].length, s, force_n, force_n, e);
                splits++;
                forced[n2++] = patches[pi]; // prefix part [s, force_n)
                forced[n2 - 1].length = force_n - s;
                if (n2 < AUDIT_MAX_PATCHES) {
                    forced[n2] = patches[pi]; // draft part [force_n, e)
                    forced[n2].start_idx = force_n;
                    forced[n2].length = e - force_n;
                    forced[n2].peak_entropy = patches[pi].peak_entropy;
                    n2++;
                }
            } else {
                forced[n2++] = patches[pi];
            }
        }
        BLT_REQUIRE(n2 <= AUDIT_MAX_PATCHES, "selfspec_audit: forced-boundary patch array overflow");
        num_patches = n2;
        memcpy(patches, forced, n2 * sizeof(blt_patch_info));
        printf("force-l=%ld: patches %zu -> %zu (%zu split)", force_l, before, num_patches, splits);
        if (splits == 0) printf("; no patch straddled byte %ld", force_l);
        printf("\n");
    }

    size_t covered = 0;
    int tiles = (num_patches > 0);
    for (size_t i = 0; i < num_patches; i++) {
        if (i == 0) {
            if (patches[i].start_idx != 0) tiles = 0;
        } else if (patches[i].start_idx != patches[i - 1].start_idx + patches[i - 1].length) {
            tiles = 0;
        }
        covered += patches[i].length;
    }
    if (covered != len) tiles = 0;
    const size_t range_lo = (num_patches > 0) ? patches[0].start_idx : 0;
    const size_t range_hi =
        (num_patches > 0) ? patches[num_patches - 1].start_idx + patches[num_patches - 1].length : 0;

    printf("patches: count=%zu range=[%zu,%zu) covered=%zu of %zu bytes\n", num_patches, range_lo, range_hi, covered,
           len);
    if (!tiles) {
        printf("*** WARNING: patches do NOT exactly tile [0,%zu) - this is a bug class worth surfacing ***\n", len);
        printf("*** WARNING: expected contiguous coverage 0..%zu, observed %zu patch(s) totalling %zu bytes ***\n", len,
               num_patches, covered);
    }

    if (print_patches) {
        for (size_t i = 0; i < num_patches; i++) {
            printf("patch %zu start=%zu len=%zu\n", i, patches[i].start_idx, patches[i].length);
        }
    }

    const size_t vocab_size = model->config.decoder_config.vocab_size;

    size_t bytes_shape[1] = {len};
    blt_tensor cand_bytes = blt_tensor_create(arena, bytes_shape, 1, BLT_DTYPE_UINT8);
    blt_tensor_upload(&cand_bytes, bytes, len);

    blt_model_enc_out enc;
    blt_model_encode(model, &cand_bytes, patches, num_patches, NULL, 0, &enc, arena);

    size_t logits_shape[2] = {len, vocab_size};
    blt_tensor logits = blt_tensor_create(arena, logits_shape, 2, BLT_DTYPE_FP32);
    blt_local_decoder_forward_ext(model->decoder, &enc.byte_hidden_out, &enc.global_out, patches, num_patches, NULL,
                                  NULL, NULL, 0, NULL, &logits, NULL, arena);

    float *logits_host = (float *)malloc(logits.numel * sizeof(float));
    BLT_REQUIRE(logits_host != NULL, "selfspec_audit: failed to stage logits");
    blt_tensor_download(&logits, logits_host, logits.numel * sizeof(float));

    size_t audited = 0;
    size_t mismatches = 0;
    size_t first_mismatch = 0;
    int have_first = 0;

    for (size_t p = (size_t)prompt_len; p < len; p++) {
        const float *row = logits_host + (p - 1) * vocab_size;
        size_t best = 0;
        float best_val = row[0];
        float second_val = -FLT_MAX;
        for (size_t v = 1; v < vocab_size; v++) {
            if (row[v] > best_val) {
                second_val = best_val;
                best_val = row[v];
                best = v;
            } else if (row[v] > second_val) {
                second_val = row[v];
            }
        }
        const float margin = best_val - second_val;
        const uint8_t committed = bytes[p];
        const uint8_t pred = (uint8_t)best;
        const int match = (committed == pred);
        const int tie = (margin < margin_threshold);
        printf("pos=%zu byte=0x%02X pred=0x%02X %s margin=%.6f%s\n", p, (unsigned)committed, (unsigned)pred,
               match ? "MATCH" : "MISMATCH", margin, tie ? " TIE" : "");
        audited++;
        if (!match) {
            if (!have_first) {
                first_mismatch = p;
                have_first = 1;
            }
            mismatches++;
        }
    }

    printf("=== SUMMARY ===\n");
    printf("audited positions: %zu\n", audited);
    printf("mismatches: %zu\n", mismatches);
    if (have_first) {
        printf("first mismatch byte offset: %zu\n", first_mismatch);
    } else {
        printf("first mismatch byte offset: none\n");
    }

    free(logits_host);
    free(bytes);
    blt_arena_destroy(scratch);
    blt_arena_destroy(arena);
    return 0;
}
