// Production inference binary for fBLT models.
// Single checkpoint, single prompt and generation.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "core/allocator.h"
#include "core/platform.h"
#include "core/backend.h"
#include "models/model.h"
#include "models/checkpoint.h"
#include "models/entropy_lm.h"
#include "models/patcher.h"
#include "models/model_builder.h"
#include "infer/block_generation.h"
#include "infer/self_speculation.h"
#include "core/generate_greedy.h"

// Method IDs for generation dispatch.
enum { M_GREEDY = 0, M_SELFSPEC, M_BLOCKDIFF, M_BLOCKDV };

typedef struct {
    const char *checkpoint;

    // Prompt source
    const char *prompt;
    const char *prompt_file;

    // Generation
    size_t new_bytes;
    int method;

    // Self-speculation (method = selfspec)
    size_t k;

    // Block generation (method = blockdiff | blockdv)
    size_t block_size;
    int unmask_eb;
    float threshold;
    int boundary_aligned;
    int adaptive;
    size_t b_min;
    size_t b_max;
    float accept_target;
    size_t adapt_window;

    // Model shape (required and must match checkpoint)
    size_t embed;
    size_t hidden;
    size_t enc_layers;
    size_t glob_layers;
    size_t dec_layers;
    int cross_last;

    // Patcher
    int fixed_patches;
    float patch_threshold_global;
    float patch_threshold_monotonic;
    size_t max_patch_length;
    const char *entropy_lm;

    // Backend
    int use_cuda;

    // I/O
    const char *output;
    uint64_t seed;
} infer_args;

static void usage(void) {
    fprintf(stderr, "usage: bin/infer --checkpoint FILE --embed E --hidden H --enc-layers N "
                    "--glob-layers N --dec-layers N --backend cpu|cuda [options]\n"
                    "\n"
                    "required:\n"
                    "  --checkpoint FILE           model checkpoint (.fblt)\n"
                    "  --embed E                   model embed dim\n"
                    "  --hidden H                  model hidden dim\n"
                    "  --enc-layers N              encoder layers\n"
                    "  --glob-layers N             global transformer layers\n"
                    "  --dec-layers N              decoder layers\n"
                    "  --backend cpu|cuda          compute backend\n"
                    "\n"
                    "prompt (exactly one):\n"
                    "  --prompt TEXT               raw bytes to use as prompt\n"
                    "  --prompt-file FILE          read prompt from file (raw bytes)\n"
                    "  (default: read from stdin until EOF)\n"
                    "\n"
                    "generation:\n"
                    "  --new-bytes N               bytes to generate (default 64)\n"
                    "  --method greedy|selfspec|blockdiff|blockdv (default greedy)\n"
                    "  --seed N                    RNG seed for random-init entropy LM (default 11)\n"
                    "\n"
                    "self-speculation (--method selfspec):\n"
                    "  --k N                       draft window size (default 8)\n"
                    "\n"
                    "block diffusion (--method blockdiff|blockdv):\n"
                    "  --block-size B              diffusion block size (default 8)\n"
                    "  --unmask confidence|eb      unmasking strategy (default confidence)\n"
                    "  --threshold F               alpha for confidence, gamma for eb (default 0.7/1.0)\n"
                    "  --boundary-aligned          commit only at patch boundaries\n"
                    "  --adaptive                  adaptive block size\n"
                    "  --b-min N                   adaptive lower bound (default 4)\n"
                    "  --b-max N                   adaptive upper bound (default 16)\n"
                    "  --accept-target F           rolling acceptance target (default 0.5)\n"
                    "  --adapt-window N            rounds per rolling average (default 8)\n"
                    "\n"
                    "model:\n"
                    "  --cross-attn all|last       cross-attention placement (default all)\n"
                    "\n"
                    "patcher:\n"
                    "  --fixed-patches             fixed-stride-4 patching (matches training)\n"
                    "  --patch-threshold-global F  global entropy threshold (default 2.5)\n"
                    "  --patch-threshold-monotonic F monotonic threshold (default 1.0)\n"
                    "  --max-patch-length N        max patch size (default 16)\n"
                    "  --entropy-lm FILE           trained entropy-LM weights (optional)\n"
                    "\n"
                    "I/O:\n"
                    "  --output FILE               write generated bytes to file (default stdout)\n");
    exit(1);
}

//----------------------------------------------------------------------
// CUDA weight upload

static void upload_model_weights(blt_model *dst, const blt_model *src) {
    const size_t n = blt_model_num_tensors(src);
    BLT_REQUIRE(n == blt_model_num_tensors(dst), "upload_model_weights: twin models disagree on tensor count");
    float *stage = NULL;
    size_t cap = 0;
    for (size_t i = 0; i < n; i++) {
        const char *name_src;
        blt_tensor *t_src;
        const char *name_dst;
        blt_tensor *t_dst;
        blt_model_tensor_at(src, i, &name_src, &t_src);
        blt_model_tensor_at(dst, i, &name_dst, &t_dst);
        BLT_REQUIRE(strcmp(name_src, name_dst) == 0, "upload_model_weights: tensor order mismatch at %zu", i);
        if (cap < t_src->numel) {
            free(stage);
            cap = t_src->numel;
            stage = (float *)malloc(cap * sizeof(float));
            BLT_REQUIRE(stage != NULL, "upload_model_weights: staging alloc failed");
        }
        blt_tensor_download(t_src, stage, blt_tensor_bytes(t_src));
        blt_tensor_upload(t_dst, stage, blt_tensor_bytes(t_dst));
    }
    free(stage);
}

static void upload_entropy_lm_weights(blt_entropy_lm *dst, const blt_entropy_lm *src) {
    blt_tensor_upload(&dst->embedding_weight, src->embedding_weight.data, blt_tensor_bytes(&src->embedding_weight));
    blt_tensor_upload(&dst->lm_head_weight, src->lm_head_weight.data, blt_tensor_bytes(&src->lm_head_weight));
    for (size_t i = 0; i < src->stack.num_layers; i++) {
        const blt_transformer_layer_storage *s = &src->stack.layer_storage[i];
        blt_transformer_layer_storage *d = &dst->stack.layer_storage[i];
        blt_tensor_upload(&d->norm1_weight, s->norm1_weight.data, blt_tensor_bytes(&s->norm1_weight));
        blt_tensor_upload(&d->attn_qkv_w, s->attn_qkv_w.data, blt_tensor_bytes(&s->attn_qkv_w));
        blt_tensor_upload(&d->attn_proj_w, s->attn_proj_w.data, blt_tensor_bytes(&s->attn_proj_w));
        blt_tensor_upload(&d->norm2_weight, s->norm2_weight.data, blt_tensor_bytes(&s->norm2_weight));
        blt_tensor_upload(&d->ffn_up_w, s->ffn_up_w.data, blt_tensor_bytes(&s->ffn_up_w));
        blt_tensor_upload(&d->ffn_gate_w, s->ffn_gate_w.data, blt_tensor_bytes(&s->ffn_gate_w));
        blt_tensor_upload(&d->ffn_down_w, s->ffn_down_w.data, blt_tensor_bytes(&s->ffn_down_w));
    }
}

//----------------------------------------------------------------------
// Prompt reading

static uint8_t *read_prompt_from_stdin(size_t *out_len) {
    size_t cap = 4096;
    size_t len = 0;
    uint8_t *buf = (uint8_t *)malloc(cap);
    BLT_REQUIRE(buf != NULL, "infer: stdin buffer alloc failed");
    for (;;) {
        if (len == cap) {
            cap *= 2;
            buf = (uint8_t *)realloc(buf, cap);
            BLT_REQUIRE(buf != NULL, "infer: stdin buffer realloc failed");
        }
        size_t n = fread(buf + len, 1, cap - len, stdin);
        len += n;
        if (n == 0) break;
    }
    *out_len = len;
    return buf;
}

static uint8_t *read_prompt_from_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    BLT_REQUIRE(f != NULL, "infer: cannot open prompt file '%s'", path);
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    BLT_REQUIRE(fsize >= 0, "infer: cannot stat prompt file '%s'", path);
    uint8_t *buf = (uint8_t *)malloc((size_t)fsize);
    BLT_REQUIRE(buf != NULL, "infer: prompt file alloc failed");
    size_t nread = fread(buf, 1, (size_t)fsize, f);
    fclose(f);
    BLT_REQUIRE(nread == (size_t)fsize, "infer: short read on '%s'", path);
    *out_len = (size_t)fsize;
    return buf;
}

//----------------------------------------------------------------------
// Method name helper

static const char *method_name(int method) {
    switch (method) {
    case M_GREEDY:
        return "greedy";
    case M_SELFSPEC:
        return "selfspec";
    case M_BLOCKDIFF:
        return "blockdiff";
    case M_BLOCKDV:
        return "blockdv";
    default:
        return "unknown";
    }
}

//----------------------------------------------------------------------
// Main

int main(int argc, char **argv) {
    // Defaults
    infer_args a;
    memset(&a, 0, sizeof(a));
    a.new_bytes = 64;
    a.method = M_GREEDY;
    a.k = 8;
    a.block_size = 8;
    a.unmask_eb = 0;
    a.threshold = 0.7f;
    a.boundary_aligned = 0;
    a.adaptive = 0;
    a.b_min = 4;
    a.b_max = 16;
    a.accept_target = 0.5f;
    a.adapt_window = 8;
    a.cross_last = 0;
    a.fixed_patches = 0;
    a.patch_threshold_global = 2.5f;
    a.patch_threshold_monotonic = 1.0f;
    a.max_patch_length = 16;
    a.use_cuda = -1;
    a.seed = 11;

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help")) {
            usage();
        } else if (!strcmp(argv[i], "--checkpoint") && i + 1 < argc) {
            a.checkpoint = argv[++i];
        } else if (!strcmp(argv[i], "--prompt") && i + 1 < argc) {
            a.prompt = argv[++i];
        } else if (!strcmp(argv[i], "--prompt-file") && i + 1 < argc) {
            a.prompt_file = argv[++i];
        } else if (!strcmp(argv[i], "--new-bytes") && i + 1 < argc) {
            a.new_bytes = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--method") && i + 1 < argc) {
            ++i;
            if (!strcmp(argv[i], "greedy")) a.method = M_GREEDY;
            else if (!strcmp(argv[i], "selfspec")) a.method = M_SELFSPEC;
            else if (!strcmp(argv[i], "blockdiff")) a.method = M_BLOCKDIFF;
            else if (!strcmp(argv[i], "blockdv")) a.method = M_BLOCKDV;
            else BLT_FATAL("infer: unknown --method '%s'", argv[i]);
        } else if (!strcmp(argv[i], "--k") && i + 1 < argc) {
            a.k = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--block-size") && i + 1 < argc) {
            a.block_size = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--unmask") && i + 1 < argc) {
            ++i;
            if (!strcmp(argv[i], "confidence")) a.unmask_eb = 0;
            else if (!strcmp(argv[i], "eb")) a.unmask_eb = 1;
            else BLT_FATAL("infer: unknown --unmask '%s' (confidence|eb)", argv[i]);
        } else if (!strcmp(argv[i], "--threshold") && i + 1 < argc) {
            a.threshold = atof(argv[++i]);
        } else if (!strcmp(argv[i], "--boundary-aligned")) {
            a.boundary_aligned = 1;
        } else if (!strcmp(argv[i], "--adaptive")) {
            a.adaptive = 1;
        } else if (!strcmp(argv[i], "--b-min") && i + 1 < argc) {
            a.b_min = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--b-max") && i + 1 < argc) {
            a.b_max = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--accept-target") && i + 1 < argc) {
            a.accept_target = atof(argv[++i]);
        } else if (!strcmp(argv[i], "--adapt-window") && i + 1 < argc) {
            a.adapt_window = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--embed") && i + 1 < argc) {
            a.embed = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--hidden") && i + 1 < argc) {
            a.hidden = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--enc-layers") && i + 1 < argc) {
            a.enc_layers = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--glob-layers") && i + 1 < argc) {
            a.glob_layers = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--dec-layers") && i + 1 < argc) {
            a.dec_layers = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--cross-attn") && i + 1 < argc) {
            ++i;
            if (!strcmp(argv[i], "all")) a.cross_last = 0;
            else if (!strcmp(argv[i], "last")) a.cross_last = 1;
            else BLT_FATAL("infer: unknown --cross-attn '%s'", argv[i]);
        } else if (!strcmp(argv[i], "--fixed-patches")) {
            a.fixed_patches = 1;
        } else if (!strcmp(argv[i], "--patch-threshold-global") && i + 1 < argc) {
            a.patch_threshold_global = atof(argv[++i]);
        } else if (!strcmp(argv[i], "--patch-threshold-monotonic") && i + 1 < argc) {
            a.patch_threshold_monotonic = atof(argv[++i]);
        } else if (!strcmp(argv[i], "--max-patch-length") && i + 1 < argc) {
            a.max_patch_length = strtoull(argv[++i], NULL, 10);
        } else if (!strcmp(argv[i], "--entropy-lm") && i + 1 < argc) {
            a.entropy_lm = argv[++i];
        } else if (!strcmp(argv[i], "--backend") && i + 1 < argc) {
            ++i;
            if (!strcmp(argv[i], "cuda")) a.use_cuda = 1;
            else if (!strcmp(argv[i], "cpu")) a.use_cuda = 0;
            else BLT_FATAL("infer: unknown --backend '%s' (cpu|cuda)", argv[i]);
        } else if (!strcmp(argv[i], "--output") && i + 1 < argc) {
            a.output = argv[++i];
        } else if (!strcmp(argv[i], "--seed") && i + 1 < argc) {
            a.seed = strtoull(argv[++i], NULL, 10);
        } else {
            BLT_FATAL("infer: unknown argument '%s'", argv[i]);
        }
    }

    // Validate required fields.
    BLT_REQUIRE(a.checkpoint != NULL, "infer: --checkpoint is required");
    BLT_REQUIRE(!(a.prompt != NULL && a.prompt_file != NULL),
                "infer: --prompt and --prompt-file are mutually exclusive");
    BLT_REQUIRE(a.embed > 0, "infer: --embed is required");
    BLT_REQUIRE(a.hidden > 0, "infer: --hidden is required");
    BLT_REQUIRE(a.enc_layers > 0, "infer: --enc-layers is required");
    BLT_REQUIRE(a.glob_layers > 0, "infer: --glob-layers is required");
    BLT_REQUIRE(a.dec_layers > 0, "infer: --dec-layers is required");
    BLT_REQUIRE(a.use_cuda >= 0, "infer: --backend cpu|cuda is required");

#ifndef BLT_WITH_CUDA
    if (a.use_cuda) {
        BLT_FATAL("infer: --backend cuda requires a CUDA=1 build");
    }
#endif

    // Adjust default threshold for EB mode.
    if (a.unmask_eb && a.threshold == 0.7f) {
        a.threshold = 1.0f;
    }

    // Read prompt.
    uint8_t *prompt_bytes;
    size_t prompt_len;
    if (a.prompt) {
        prompt_bytes = (uint8_t *)a.prompt;
        prompt_len = strlen(a.prompt);
    } else if (a.prompt_file) {
        prompt_bytes = read_prompt_from_file(a.prompt_file, &prompt_len);
    } else {
        prompt_bytes = read_prompt_from_stdin(&prompt_len);
    }

    // Print startup diagnostics.
    fprintf(stderr, "[infer] checkpoint: %s\n", a.checkpoint);
    fprintf(stderr, "[infer] backend: %s\n", a.use_cuda ? "cuda" : "cpu");
    fprintf(stderr, "[infer] method: %s\n", method_name(a.method));
    fprintf(stderr, "[infer] patcher: %s\n", a.fixed_patches ? "fixed-stride-4" : "entropy (thr, max)");
    fprintf(stderr, "[infer] entropy LM: %s\n", a.entropy_lm ? a.entropy_lm : "random-init");
    fprintf(stderr, "[infer] prompt: %zu bytes\n", prompt_len);
    fprintf(stderr, "[infer] generating: %zu new bytes\n", a.new_bytes);

    // Create arenas.
    const blt_backend dev = a.use_cuda ? BLT_BACKEND_CUDA : BLT_BACKEND_CPU;
    blt_arena *arena = blt_arena_create(160 * 1024 * 1024, dev);
    blt_arena *scratch = blt_arena_create(256 * 1024 * 1024, dev);

    // Build model config.
    blt_model_config cfg;
    blt_model_config_defaults(&cfg, a.embed, a.hidden, a.enc_layers, a.glob_layers, a.dec_layers, 512, a.cross_last);

    // Model loading.
    blt_model *model;
    blt_entropy_lm *lm;
    if (a.use_cuda) {
        // Host twin receives checkpoint; weights are uploaded to device.
        blt_arena *host_arena = blt_arena_create(160 * 1024 * 1024, BLT_BACKEND_CPU);
        blt_model *host_model = blt_model_create(host_arena, &cfg);
        blt_model_load(host_model, a.checkpoint);

        model = blt_model_create(arena, &cfg);
        upload_model_weights(model, host_model);

        lm = blt_make_entropy_lm(host_arena, 512, a.entropy_lm, a.seed);
        blt_entropy_lm *lm_d = blt_entropy_lm_create(arena, &lm->config);
        upload_entropy_lm_weights(lm_d, lm);
        lm = lm_d;

        blt_arena_destroy(host_arena);
        fprintf(stderr, "[infer] backend cuda: model uploaded\n");
    } else {
        model = blt_model_create(arena, &cfg);
        blt_model_load(model, a.checkpoint);
        lm = blt_make_entropy_lm(arena, 512, a.entropy_lm, a.seed);
    }

    // Patcher config.
    blt_patcher_config pcfg;
    blt_make_patcher_cfg(&pcfg, a.fixed_patches, a.patch_threshold_global, a.patch_threshold_monotonic,
                         a.max_patch_length);

    // Allocate output buffer.
    const size_t total_out = prompt_len + a.new_bytes;
    uint8_t *output = (uint8_t *)malloc(total_out);
    BLT_REQUIRE(output != NULL, "infer: output buffer alloc failed");

    // Generation dispatch.
    blt_infer_stats st;
    memset(&st, 0, sizeof(st));

    double t0 = blt_time_sec();

    switch (a.method) {
    case M_GREEDY:
        blt_generate_greedy(model, lm, &pcfg, prompt_bytes, prompt_len, a.new_bytes, output, scratch);
        st.nfe_encoder_global = a.new_bytes;
        st.nfe_decoder = a.new_bytes;
        break;
    case M_SELFSPEC: {
        blt_self_spec_config sc;
        memset(&sc, 0, sizeof(sc));
        sc.window_k = a.k;
        sc.d0_mode = BLT_D0_LEARNED;
        blt_generate_greedy_selfspec(model, lm, &pcfg, prompt_bytes, prompt_len, a.new_bytes, output, &sc, &st,
                                     scratch);
        break;
    }
    case M_BLOCKDIFF: {
        blt_block_gen_config gc;
        memset(&gc, 0, sizeof(gc));
        gc.block_size = a.block_size;
        gc.d0_mode = BLT_D0_LEARNED;
        gc.opts.strategy = a.unmask_eb ? BLT_UNMASK_EB : BLT_UNMASK_CONFIDENCE;
        gc.opts.threshold = a.threshold;
        gc.boundary_aligned = a.boundary_aligned;
        if (a.adaptive) {
            gc.B_min = a.b_min;
            gc.B_max = a.b_max;
            gc.accept_target = a.accept_target;
            gc.adapt_window = a.adapt_window;
        }
        blt_generate_greedy_blockdiff(model, lm, &pcfg, prompt_bytes, prompt_len, a.new_bytes, output, &gc, &st,
                                      scratch);
        break;
    }
    case M_BLOCKDV: {
        blt_block_gen_config gc;
        memset(&gc, 0, sizeof(gc));
        gc.block_size = a.block_size;
        gc.d0_mode = BLT_D0_LEARNED;
        gc.opts.strategy = a.unmask_eb ? BLT_UNMASK_EB : BLT_UNMASK_CONFIDENCE;
        gc.opts.threshold = a.threshold;
        gc.boundary_aligned = a.boundary_aligned;
        gc.verifier_model = NULL;
        if (a.adaptive) {
            gc.B_min = a.b_min;
            gc.B_max = a.b_max;
            gc.accept_target = a.accept_target;
            gc.adapt_window = a.adapt_window;
        }
        blt_generate_greedy_blockdiff_verify(model, lm, &pcfg, prompt_bytes, prompt_len, a.new_bytes, output, &gc, &st,
                                             scratch);
        break;
    }
    }

    double elapsed_ms = (blt_time_sec() - t0) * 1000.0;

    // Write generated bytes to output.
    FILE *outfp = stdout;
    if (a.output) {
        outfp = fopen(a.output, "wb");
        BLT_REQUIRE(outfp != NULL, "infer: cannot open output file '%s'", a.output);
    }
    size_t nwritten = fwrite(output, 1, total_out, outfp);
    if (nwritten != total_out) {
        BLT_FATAL("infer: short write (%zu of %zu bytes)", nwritten, total_out);
    }
    if (a.output) {
        fclose(outfp);
    }

    // Print stats to stderr
    fprintf(stderr, "[infer] nfe_enc_glob=%zu, nfe_dec=%zu, drafted=%zu, accepted=%zu (%.1f%%)\n",
            st.nfe_encoder_global, st.nfe_decoder, st.bytes_drafted, st.bytes_accepted,
            (double)(100.0f * blt_infer_stats_acceptance_rate(&st)));
    fprintf(stderr, "[infer] wall_clock: %.3f ms\n", elapsed_ms);

    // Cleanup.
    free(output);
    if (a.prompt_file || (!a.prompt && !a.prompt_file)) {
        free(prompt_bytes);
    }
    blt_arena_destroy(scratch);
    blt_arena_destroy(arena);

    return 0;
}
